
[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1"

[window]
position = "None"
dynamic_padding = true
decorations = "Full"
opacity = 0.8
blur = false
startup_mode = "Maximized"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 8
y = 8

[scrolling]
history = 10000
multiplier = 3

[bell]
command = { program = "paplay", args = [
  "/usr/share/sounds/freedesktop/stereo/dialog-error.oga",
] }

## SELECTION ------------------------------------------------------
[selection]
save_to_clipboard = true

## CURSOR ---------------------------------------------------------
[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
thickness = 0.15

[cursor.style]
shape = "beam"
blinking = "On"

## MOUSE ----------------------------------------------------------
[mouse]
hide_when_typing = false

## HINTS ----------------------------------------------------------
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

## DEBUG ----------------------------------------------------------
[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false

[general]

live_config_reload = true
ipc_socket = true
import = [
  "~/dotfiles/alacritty/colorschemes/catppuccin-mocha.toml",
  "~/dotfiles/alacritty/fonts.toml",
]
