## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Colors configuration -------------------------------------

# [colors.primary]
# background = "#1E2128"
# foreground = "#ABB2BF"
#
# [colors.normal]
# black   = "#32363D"
# red     = "#E06B74"
# green   = "#98C379"
# yellow  = "#E5C07A"
# blue    = "#62AEEF"
# magenta = "#C778DD"
# cyan    = "#55B6C2"
# white   = "#ABB2BF"
#
# [colors.bright]
# black   = "#50545B"
# red     = "#EA757E"
# green   = "#A2CD83"
# yellow  = "#EFCA84"
# blue    = "#6CB8F9"
# magenta = "#D282E7"
# cyan    = "#5FC0CC"
# white   = "#B5BCC9"
[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x9699a8"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xa9b1d6"
