
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

#? █▀█ █▀▀ █▀▀ █▀▀ █▀█ █▀▀ █▄░█ █▀▀ █▀▀
#? █▀▄ ██▄ █▀░ ██▄ █▀▄ ██▄ █░▀█ █▄▄ ██▄

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄


#?  Reference 
# Configurations below are for reference ONLY
# They are not essential for HyDE to work but can be used to enhance QOL
# Copy the config line and paste it in the Users section to use it
# This is to prevent bloating users configuration files when not needed

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 4
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = true
    }

    shadow {
        enabled = false
    }
}

layerrule = blur,waybar

workspace = special:Gemini
bind = $mainMod, C , exec, ~/dotfiles/scripts/toggle_gemini.sh

windowrulev2 = float, initialTitle:^(gemini.google.com_/app)$
windowrulev2 = size 20% 75%,initialTitle:^(gemini.google.com_/app)$
windowrulev2 = move 100%-w-10%,initialTitle:^(gemini.google.com_/app)$
windowrulev2 = nodim,initialTitle:^(gemini.google.com_/app)$

windowrulev2 = float, initialClass:^(com.mitchellh.ghostty)$
windowrulev2 = size 85% 85%,initialClass:^(com.mitchellh.ghostty)$
windowrulev2 = nodim,initialClass:^(com.mitchellh.ghostty)$

input {
   repeat_rate = 80
   repeat_delay = 200
}
misc {
   focus_on_activate = true
}


# // █▀▀ █▄░█ █░█
# // ██▄ █░▀█ ▀▄▀

env = MANGOHUD,1
env = MANGOHUD_DLSYM,1

# Enable Wayland compatibility
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = GTK_USE_PORTAL,1
env = QT_QPA_PLATFORMTHEME,xdgdesktopportal
env = QT_QPA_PLATFORM,wayland


# // █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# // █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

bind = Ctrl+Alt+Shift, R, pass, ^(com\.obsproject\.Studio)$ # toggle obs screen recording // install obs flatpak
bind = $mainMod+Shift, G, exec, pkill -x rofi || $scrPath/gamelauncher.sh # launch steam game launcher // install steam
bind = $mainMod, Period, exec, emote # launch emoji selector // install emote
bind = $mainMod+Alt, XF86MonBrightnessDown, exec, hyprshade on blue-light-filter # enable blue light filter // install hyprshade
bind = $mainMod+Alt, XF86MonBrightnessUp, exec, hyprshade off # disable blue light filter // install hyprshade
bind = $mainMod, R, exec, hyprctl dispatch closewindow address:$(hyprctl clients -j | jq -r --arg target rambox '.[] | select(.initialtitle | test($target; "i")) | .address' | head -n 1); rambox

bind = ,mouse:276, killactive


# // █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# // █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

exec-once = swayidle -w timeout 600 'swaylock' timeout 900 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' # lock after 10 mins, sleep after 15 mins // install swayidle
exec-once = swayidle -w timeout 1200 'swaylock; hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 1800 'systemctl suspend' # lock and sleep after 20 mins, suspend after 30 mins // install swayidle

exec-once = libinput-gestures // install libinput-gestures

exec-once = swayosd-server # enable swayosd service
exec-once = `pkexec swayosd-libinput-backend` # swayosd service for keyboard input (requires to be run in a subshell)

exec-once = spotify &
exec-once = rambox &
exec-once = discord &


# // █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# // ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

windowrulev2 = opacity 0.60 0.60,class:^(Steam)$
windowrulev2 = opacity 0.60 0.60,class:^(steam)$
windowrulev2 = opacity 0.60 0.60,class:^(steamwebhelper)$
windowrulev2 = opacity 0.60 0.60,class:^(Spotify)$


# // █░█ █▀▄▀█
# // ▀▄▀ █░▀░█

bind = Ctrl+Alt_L, V, submap, passthrough
submap = passthrough
bind = Ctrl+Alt_L, V, submap, reset
submap = reset
