# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

input {
    repeat_rate = 60
}

general {
    border_size = 0
}

decoration {
    rounding = 20
}
