include hyde.conf

cursor_shape                block
font_size                   12

# font_family                 JetBrainsMono Nerd Font
font_family                 IosevkaTerm Nerd Font

window_padding_width        8
confirm_os_window_close     0

enable_audio_bell           no
background_opacity          0.5
# background_blur             1
