foreground              #FFFFFF
background              #171616
selection_foreground    #171616
selection_background    #FFFFFF
cursor                  #E95896
cursor_text_color       #ACB8B3

active_tab_foreground     #171616
active_tab_background     #DEBCCF
inactive_tab_foreground   #DEBCCF
inactive_tab_background   #171616

# black
color0      #522929
color8      #8F5757

# red
color1      #FFCCE2
color9      #F0AAC8

# green
color2      #FFCCE3
color10     #F0AAC9

# yellow
color3      #FFCCE8
color11     #F0AAD1

# blue
color4      #E69A9A
color12     #E69A9A

# magenta
color5      #E69ABB
color13     #E69ABB

# cyan
color6      #E69AC4
color14     #E69AC4

# white
color7      #FFCCE2
color15     #F0AAC8
