foreground              #FFFFFF
background              #424242
selection_foreground    #424242
selection_background    #FFFFFF
cursor                  #F86FAB
cursor_text_color       #0B0D0C

active_tab_foreground     #424242
active_tab_background     #E0E0E6
inactive_tab_foreground   #E0E0E6
inactive_tab_background   #424242

# black
color0      #522929
color8      #8F5757

# red
color1      #FFCCE2
color9      #F0AAC9

# green
color2      #FFCCE2
color10     #F0AAC8

# yellow
color3      #CCCCFF
color11     #AAAAF0

# blue
color4      #E69A9A
color12     #E69A9A

# magenta
color5      #E69ABB
color13     #E69ABB

# cyan
color6      #9A9AE6
color14     #9A9AE6

# white
color7      #FFCCE2
color15     #F0AAC9
